#pragma once

#define VERSION_MAJOR 0
#define VERSION_MINOR 0
#define VERSION_PATCH 1
#define VERSION_BUILD 12

#define VERSION_FULL VERSION_MAJOR,VERSION_MINOR,VERSION_PATCH,VERSION_BUILD


#define _VERSION_STRINGIFY_INTERNAL(x) #x
#define _VERSION_STRINGIFY(x) _VERSION_STRINGIFY_INTERNAL(x)

#define VERSION_FULL_STRING _VERSION_STRINGIFY(VERSION_MAJOR) "." _VERSION_STRINGIFY(VERSION_MINOR) "." _VERSION_STRINGIFY(VERSION_PATCH) "." _VERSION_STRINGIFY(VERSION_BUILD)

// For RC files (must be comma-separated)
#define VERSION_FILEVERSION VERSION_FULL
#define VERSION_PRODUCTVERSION VERSION_FULL
#define VERSION_FILEVERSION_STRING _VERSION_STRINGIFY(VERSION_MAJOR) "." _VERSION_STRINGIFY(VERSION_MINOR) "." _VERSION_STRINGIFY(VERSION_PATCH) "." _VERSION_STRINGIFY(VERSION_BUILD)
#define VERSION_PRODUCTVERSION_STRING _VERSION_STRINGIFY(VERSION_MAJOR) "." _VERSION_STRINGIFY(VERSION_MINOR) "." _VERSION_STRINGIFY(VERSION_PATCH) "." _VERSION_STRINGIFY(VERSION_BUILD)
